### ISSUE TITLE
Local Development Routing Error [bug]

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Quansight/qhub-cloud#347] opened 2021-03-01 16:33 UTC
I'm getting this message when following the steps for local qhub development found at https://github.com/Quansight/qhub-cloud/blob/dev/docs/source/06_developers_contrib_guide/04_local_development.md.  I can manually enable port forwarding using k9s on the proxy pod to work around this.
```
time="2021-03-01T16:29:38Z" level=error msg="the router dask-gateway-dev-jupyter-github-actions-qhub-dev@kubernetes uses a non-existent resolver: default"                 
time="2021-03-01T16:29:38Z" level=error msg="the router dask-gateway-dev-jupyter-github-actions-qhub-dev-gateway@kubernetes uses a non-existent resolver: default" 
```

**Comment by costrouc** [comment] 2021-03-02 02:28
@Adam-D-Lewis and @viniciusdc I was not able to reproduce this bug on my NixOS machine. This leads me to believe that this is a networking issue when connecting to the minikube docker cluster. Will need to meet with you all to debug further.

**Comment by costrouc** [comment] 2021-03-03 02:56
Closing in favor of https://github.com/Quansight/qhub-cloud/issues/361

**Closed by costrouc** 2021-03-03 02:56 UTC
Labels: type: bug 🐛
