### ISSUE TITLE
split infrastructure files into infrastructure, kubernetes folder

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub-cloud#271] opened 2021-01-26 15:48 UTC
Currently all of the terrraform files are in a single directory. Split out kubernetes files into a separate `kubernetes` directory so that the repo is easier to maintain.

**Comment by laisbsc** [comment] 2021-02-09 14:57
Close since it is a duplicate of #305.

**Closed by laisbsc** 2021-02-09 14:57 UTC
Labels: type: duplicate
