### ISSUE TITLE
Allow for customization of jupyterlab theme

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub-cloud#142] opened 2020-10-23 21:33 UTC
- [ ] ensure support for unicode test (specifically spanish)
- [ ] allow for customized landing pages
- [ ] ensure the configuration is specific to qhub

The changes will be made in:
https://github.com/quansight/qhub-jupyterhub-theme

**Comment by laisbsc** [comment] 2021-01-07 19:06
@aktech suggested that we export the theme to a config file so it makes it easier to customize it (#175). Any suggestions @tylerpotts @tonyfast?

**Comment by costrouc** [comment] 2021-02-25 14:53
Duplicate of https://github.com/Quansight/qhub-cloud/issues/142

**Closed by costrouc** 2021-02-25 14:53 UTC
Labels: type: enhancement, type: theming
